permissions:
  contents: write

name: Lint and Format Workflow

on:
  workflow_call: #

jobs:
  format-and-lint:
    name: Format & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: npm i

      - name: Run Prettier
        run: npm run format

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "✨ Apply Prettier formatting"
          git push
        continue-on-error: true # Evita fallos si no hay cambios
